from __future__ import annotations

DATABASE_URL_ENV = "DATABASE_URL"
DEFAULT_USER_TOKEN_ENV = "MEMORY_DEFAULT_USER_TOKEN"
REST_API_ENABLED_ENV = "MEMORY_REST_API_ENABLED"
MEMORY_CONFIG_PATH_ENV = "MEMORY_CONFIG_PATH"

LEGACY_EMBEDDING_PROVIDER_ENV = "EMBEDDING_PROVIDER"
LEGACY_EMBEDDING_DIMENSION_ENV = "MEMORY_EMBEDDING_DIMENSION"
LEGACY_OLLAMA_BASE_URL_ENV = "OLLAMA_BASE_URL"
LEGACY_OLLAMA_EMBEDDING_MODEL_ENV = "OLLAMA_EMBEDDING_MODEL"
LEGACY_OLLAMA_TIMEOUT_SECONDS_ENV = "OLLAMA_TIMEOUT_SECONDS"

CLOUDFLARE_ACCOUNT_ID_ENV = "CLOUDFLARE_ACCOUNT_ID"
CLOUDFLARE_API_TOKEN_ENV = "CLOUDFLARE_API_TOKEN"

OLLAMA_PROVIDER = "ollama"
CLOUDFLARE_PROVIDER = "cloudflare"
EMBEDDING_PROVIDERS = {OLLAMA_PROVIDER, CLOUDFLARE_PROVIDER}
SUMMARY_PROVIDERS = {CLOUDFLARE_PROVIDER}

DEFAULT_EMBEDDING_PROVIDER = OLLAMA_PROVIDER
DEFAULT_EMBEDDING_DIMENSION = 1024
DEFAULT_OLLAMA_EMBEDDING_MODEL = "qwen3-embedding:0.6b"
DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434"
DEFAULT_OLLAMA_TIMEOUT_SECONDS = 30.0

DEFAULT_CLOUDFLARE_EMBEDDING_MODEL = "@cf/baai/bge-large-en-v1.5"
DEFAULT_CLOUDFLARE_BASE_URL = "https://api.cloudflare.com/client/v4"
DEFAULT_CLOUDFLARE_TIMEOUT_SECONDS = 30.0

DEFAULT_SUMMARY_PROVIDER = CLOUDFLARE_PROVIDER
DEFAULT_CLOUDFLARE_SUMMARY_MODEL = "@cf/meta/llama-3.1-8b-instruct-fp8"
DEFAULT_CLOUDFLARE_SUMMARY_TIMEOUT_SECONDS = 60.0
DEFAULT_CLOUDFLARE_SUMMARY_MAX_TOKENS = 1200
DEFAULT_CLOUDFLARE_SUMMARY_TEMPERATURE = 0.2
DEFAULT_SUMMARY_SOURCE_MAX_CHARS = 24000

DEFAULT_DAILY_DIARY_TIMEZONE = "UTC"

DEFAULT_MAX_CHUNK_CHARS = 1800
DEFAULT_CHUNK_OVERLAP_CHARS = 200

DEFAULT_RECENT_DIARY_LOOKBACK_DAYS = 2
DEFAULT_RECENT_DIARY_MAX_ITEMS = 3
DEFAULT_RECENT_DIARY_MIN_SCORE = 0.72
DEFAULT_RECENT_DIARY_MAX_CHARS = 2000
DEFAULT_TAG_RETRIEVAL_MIN_SCORE = 0.72
DEFAULT_TAG_RETRIEVAL_MAX_TAGS = 5
DEFAULT_TAG_RETRIEVAL_TAG_WEIGHT = 0.4
DEFAULT_LINK_EXPANSION_MAX_ITEMS = 3
DEFAULT_LINK_EXPANSION_SOURCE_LIMIT = 5
DEFAULT_LINK_EXPANSION_SOURCE_WEIGHT = 0.4

DEFAULT_MCP_HTTP_ENABLED = False
DEFAULT_MCP_HTTP_HOST = "127.0.0.1"
DEFAULT_MCP_HTTP_PORT = 8001
DEFAULT_MCP_HTTP_PATH = "/mcp"
DEFAULT_MCP_HTTP_PUBLIC_URL = "http://127.0.0.1:8001"
DEFAULT_MCP_HTTP_ALLOWED_HOSTS = ("127.0.0.1:*", "localhost:*", "[::1]:*")
DEFAULT_MCP_HTTP_ALLOWED_ORIGINS = (
    "http://127.0.0.1:*",
    "http://localhost:*",
    "http://[::1]:*",
)
DEFAULT_MCP_HTTP_MAX_REQUEST_BODY_SIZE = 4_194_304
